# Generated by Django 5.0.1 on 2026-03-01 15:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "situation_familiale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CELIBATAIRE", "Célibataire"),
                            ("MARIE", "Marié"),
                            ("PACSE", "Pacsé"),
                            ("CONCUBINAGE", "En concubinage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "utilisateurs",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OffreBancaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banque", models.CharField(max_length=100)),
                (
                    "type_credit",
                    models.CharField(
                        choices=[
                            ("ETUDIANT", "Crédit Étudiant"),
                            ("IMMOBILIER", "Crédit Immobilier"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "taux_interet",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="En pourcentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("duree_min_mois", models.IntegerField(blank=True, null=True)),
                ("duree_max_mois", models.IntegerField(blank=True, null=True)),
                (
                    "montant_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("actif", models.BooleanField(default=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Offre Bancaire",
                "verbose_name_plural": "Offres Bancaires",
                "db_table": "offres_bancaires",
                "unique_together": {("banque", "type_credit", "duree_min_mois")},
            },
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_credit",
                    models.CharField(
                        choices=[
                            ("ETUDIANT", "Crédit Étudiant"),
                            ("IMMOBILIER", "Crédit Immobilier"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("CREEE", "Créée"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminée"),
                            ("ERREUR", "Erreur"),
                        ],
                        default="CREEE",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation",
                "verbose_name_plural": "Simulations",
                "db_table": "simulations",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ResultatSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("PRUDENT", "Prudent"),
                            ("EQUILIBRE", "Équilibré"),
                            ("CONFORTABLE", "Confortable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("taux_utilise", models.DecimalField(decimal_places=3, max_digits=5)),
                ("mensualite", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cout_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "taux_endettement_nouveau",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("reste_a_vivre", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "score_faisabilite",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "offre_bancaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="simulation.offrebancaire",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats",
                        to="simulation.simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat de Simulation",
                "verbose_name_plural": "Résultats de Simulations",
                "db_table": "resultats_simulations",
            },
        ),
        migrations.CreateModel(
            name="ProjetCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_souhaite",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(100)],
                    ),
                ),
                (
                    "duree_mois",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "apport_personnel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projet_credit",
                        to="simulation.simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet de Crédit",
                "verbose_name_plural": "Projets de Crédit",
                "db_table": "projets_credit",
            },
        ),
        migrations.CreateModel(
            name="ProfilFinancier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "situation_familiale",
                    models.CharField(
                        choices=[
                            ("CELIBATAIRE", "Célibataire"),
                            ("MARIE", "Marié"),
                            ("PACSE", "Pacsé"),
                            ("CONCUBINAGE", "En concubinage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ville", models.CharField(max_length=100)),
                (
                    "revenus_mensuels",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "charges_logement",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Loyer ou mensualité crédit immobilier",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "charges_credits",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total des mensualités des crédits en cours",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "charges_autres",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Autres charges (voiture, assurance, etc.)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("CDI", "CDI"),
                            ("CDD", "CDD"),
                            ("STAGE", "Stage"),
                            ("ALTERNANCE", "Alternance"),
                            ("TRAVAILLEUR_INDEPENDANT", "Travailleur indépendant"),
                            ("ASSIMILE_SALARIE", "Assimilé salarié"),
                            ("SANS_EMPLOI", "Sans emploi"),
                            ("RETRAITE", "Retraité"),
                            ("ETUDIANT", "Étudiant"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "anciennete_emploi_mois",
                    models.IntegerField(
                        help_text="En mois",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_financier",
                        to="simulation.simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Financier",
                "verbose_name_plural": "Profils Financiers",
                "db_table": "profils_financiers",
            },
        ),
        migrations.CreateModel(
            name="ExplicationIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField()),
                ("recommandations", models.TextField(blank=True)),
                ("avertissements", models.TextField(blank=True, null=True)),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                ("temps_generation_ms", models.IntegerField(default=0)),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explication_ia",
                        to="simulation.simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Explication IA",
                "verbose_name_plural": "Explications IA",
                "db_table": "explications_ia",
            },
        ),
    ]
